### ISSUE TITLE
Call to undefined function

### ISSUE THREAD

**Issue by alfredsx** [XoopsModules25x/xnewsletter#20]
Fehler: Error: Call to undefined function mysql_fetch_array() in Datei /modules/xnewsletter/plugins/xoopsuser.php Zeile 73

Xoops 2.5.9
PHP 7.1

**Comment by alfredsx** [comment]
Edit Line 73 from:
while ($lineArray = mysql_fetch_array($result_users)) {
to:
while ($lineArray = $xoopsDB->fetchBoth($result_users)) {

**Comment by ggoffy** [comment]
fixed by commits of zyspec
