### ISSUE TITLE
undefined function mysql_query()

### ISSUE THREAD

**Issue by alfredsx** [XoopsModules25x/xnewsletter#21]
Error: Call to undefined function mysql_query() in Datei /modules/xnewsletter/include/functions.php Zeile 338

Fix:
replace the line 338
if(!$subscriber = mysql_query($sql)) die ("MySQL-Error in xnewsletter_pluginCheckEmail: " . mysql_error());
to:
if(!$subscriber = $xoopsDB->query($sql)) die ("MySQL-Error in xnewsletter_pluginCheckEmail: " . $xoopsDB->error());

and replace Line 339 from:
$row_result = mysql_fetch_assoc($subscriber);
to
$row_result = $xoopsDB->fetchArray($subscriber);

**Comment by ggoffy** [comment]
fixed by commits of zyspec
