### ISSUE TITLE
deprecated function (PHP >= 7.2)

### ISSUE THREAD

**Issue by alfredsx** [XoopsModules25x/xnewsletter#23]
<xoops-url>/modules/xnewsletter/admin/accounts.php?op=check_account&accounts_id=x

The each() function is deprecated. This message will be suppressed on further calls in Datei /modules/xnewsletter/admin/accounts.php Zeile 118

The each() function is deprecated. This message will be suppressed on further calls in Datei /modules/xnewsletter/admin/accounts.php Zeile 138

**Comment by alfredsx** [comment]
while (list( $key, $val) = each ($folders)) {

replace this with 

foreach($folders as $key => $val) {

**Comment by ggoffy** [comment]
fixed. thank you
